CREATE DATABASE DEMOSTRACION

GO

USE DEMOSTRACION

GO

CREATE TABLE PERSONAS(
ID INT PRIMARY KEY IDENTITY,
NOMBRES VARCHAR(100),
APELLIDOP VARCHAR(100),
APELLIDOM VARCHAR(100))

INSERT INTO PERSONAS (NOMBRES, APELLIDOP, APELLIDOM) VALUES ('SONIA', 'CAMPOVERDE', 'QUICHIMBO')
INSERT INTO PERSONAS (NOMBRES, APELLIDOP, APELLIDOM) VALUES ('ROMEL', 'RAMON', 'HURTADO')
INSERT INTO PERSONAS (NOMBRES, APELLIDOP, APELLIDOM) VALUES ('ROSMERY', 'RAMON', 'CAMPOVERDE')

SELECT *
INTO #PERSONAS_TEMP
FROM PERSONAS
GO

SELECT * FROM #PERSONAS_TEMP

SELECT TOP 2 * FROM #PERSONAS_TEMP
ORDER BY NOMBRES

CREATE TABLE PERSONAS2(
ID INT PRIMARY KEY IDENTITY,
NOMBRES VARCHAR(100),
APELLIDOP VARCHAR(100),
APELLIDOM VARCHAR(100))

INSERT INTO PERSONAS2(NOMBRES, APELLIDOP, APELLIDOM) VALUES ('DANNY', 'CAMPOVERDE', 'MALDONADO')
INSERT INTO PERSONAS2 (NOMBRES, APELLIDOP, APELLIDOM) VALUES ('VALERIA', 'RAMON', 'CELI')
INSERT INTO PERSONAS2 (NOMBRES, APELLIDOP, APELLIDOM) VALUES ('CRISTIAN', 'CAMPOVERDE', 'ARMIJOS')


SELECT *
INTO #PERSONAS_TEMP2
FROM PERSONAS2
GO

SELECT * FROM #PERSONAS_TEMP

DROP TABLE #PERSONAS_TEMP2
DROP TABLE #PERSONAS_TEMP
DROP TABLE PERSONAS2
DROP TABLE PERSONAS

CREATE TABLE CLIENTES(
ClienteID INT PRIMARY KEY IDENTITY,
NOMBRECLIENTE VARCHAR(100),
TELEFONO VARCHAR(20))

INSERT INTO CLIENTES (NOMBRECLIENTE, TELEFONO) VALUES ('DANNY CAMPOVERDE', '0985673410')
INSERT INTO CLIENTES (NOMBRECLIENTE, TELEFONO) VALUES ('VALERIA RAMON', '0914673290')
INSERT INTO CLIENTES (NOMBRECLIENTE, TELEFONO) VALUES ('CRISTIAN ARMIJOS', '0956782109')
INSERT INTO CLIENTES (NOMBRECLIENTE, TELEFONO) VALUES ('SONIA CAMPOVERDE', '0956903621')

SELECT * FROM CLIENTES

CREATE TABLE PEDIDOS(
PEDIDOID INT,
ClienteID INT,
FACTURA VARCHAR(20))

INSERT INTO PEDIDOS (PEDIDOID, ClienteID, FACTURA) VALUES (234, 3, '160')
INSERT INTO PEDIDOS (PEDIDOID, ClienteID, FACTURA) VALUES (235, 1, '48')
INSERT INTO PEDIDOS (PEDIDOID, ClienteID, FACTURA) VALUES (236, 2, '64')
INSERT INTO PEDIDOS (PEDIDOID, ClienteID, FACTURA) VALUES (237, 3, '92')

SELECT * FROM PEDIDOS
 
SELECT *
INTO #CLIENTES_TEMP
FROM CLIENTES
GO

SELECT *
INTO #PEDIDOS_TEMP
FROM PEDIDOS
GO

SELECT * FROM #CLIENTES_TEMP
SELECT * FROM #PEDIDOS_TEMP

SELECT #CLIENTES_TEMP.NOMBRECLIENTE, #PEDIDOS_TEMP.PEDIDOID FROM #CLIENTES_TEMP
INNER JOIN #PEDIDOS_TEMP ON #CLIENTES_TEMP.ClienteID=#PEDIDOS_TEMP.ClienteID
ORDER BY #CLIENTES_TEMP.NOMBRECLIENTE;


SELECT #CLIENTES_TEMP.NOMBRECLIENTE, #PEDIDOS_TEMP.PEDIDOID
FROM #CLIENTES_TEMP LEFT JOIN #PEDIDOS_TEMP
ON #CLIENTES_TEMP.ClienteID=#PEDIDOS_TEMP.ClienteID
ORDER BY #CLIENTES_TEMP.NOMBRECLIENTE;


SELECT #PEDIDOS_TEMP.PEDIDOID, #CLIENTES_TEMP.NOMBRECLIENTE
FROM #CLIENTES_TEMP RIGHT JOIN #PEDIDOS_TEMP
ON #CLIENTES_TEMP.ClienteID=#PEDIDOS_TEMP.ClienteID
ORDER BY #PEDIDOS_TEMP.ClienteID;


SELECT #CLIENTES_TEMP.NOMBRECLIENTE, #PEDIDOS_TEMP.PEDIDOID
FROM #CLIENTES_TEMP
LEFT JOIN #PEDIDOS_TEMP ON #CLIENTES_TEMP.ClienteID=#PEDIDOS_TEMP.ClienteID
UNION
SELECT #CLIENTES_TEMP.NOMBRECLIENTE, #PEDIDOS_TEMP.PEDIDOID
FROM #CLIENTES_TEMP
RIGHT JOIN #PEDIDOS_TEMP ON #CLIENTES_TEMP.ClienteID=#PEDIDOS_TEMP.ClienteID;

SELECT COUNT(*) AS [TOTALROWCOUNT] FROM #CLIENTES_TEMP;